services:

   oboa_db:
      image: mdillon/postgis
      container_name: oboa_db
      restart: always
      shm_size: 512M
      command: -c max_connections=5000 -c max_locks_per_transaction=5000
      networks:
         - boa_network

   oboa:
      build:
         context: .
         dockerfile: Dockerfile.dev
         args:
            UID_HOST_USER: ${UID_HOST_USER:-1000}
            GID_HOST_USER: ${GID_HOST_USER:-1000}
      container_name: oboa
      restart: always
      hostname: oboa
      user: "${UID_HOST_USER:-1000}:${GID_HOST_USER:-1000}"
      environment:
         - OBOA_DDBB_HOST=oboa_db
         - OBOA_RESOURCES_PATH=/oboa/src/config
         - OBOA_LOG_PATH=/log
         - OBOA_SCHEMAS_PATH=/oboa/src/schemas
         - OBOA_POLLING_DIR=/oboa_polling
         - OBOA_PROCESSING_DIR=/oboa_processing
         - OBOA_DAEMON_PID_FILE=/tmp/oboa.pid
         - PYTHONDONTWRITEBYTECODE=1
      volumes:
         - .:/oboa:rw
      shm_size: 512M
      networks:
         - boa_network

networks:
   boa_network:
      name: boa_network
