# Base the image on Rocky Linux (Red Hat compatible)
FROM rockylinux:9

ARG UID_HOST_USER=1000
ARG GID_HOST_USER=1000

USER root

RUN groupadd -o -g ${GID_HOST_USER} boa && useradd -m -o -r -u ${UID_HOST_USER} -g boa boa

RUN yum install -y epel-release

RUN yum install --allowerasing -y \
    glibc-langpack-en \
    less \
    make \
    postgresql \
    postgresql-devel \
    procps \
    python3 \
    python3-devel \
    python3-pip \
    redhat-rpm-config \
    which

RUN pip3 install wheel

RUN mkdir /log \
    /resources_path \
    /schemas \
    /datamodel \
    /oboa_polling \
    /oboa_processing \
    /oboa_error \
    /oboa \
    /aboa

RUN chown -R boa:boa /log /resources_path /schemas /datamodel /oboa_polling /oboa_processing /oboa_error /oboa /aboa

RUN mkdir /usr/local/python-packages
RUN chown -R boa:boa /usr/local/python-packages

RUN pip3 install --target=/usr/local/python-packages \
    "sqlalchemy==1.3.22" \
    "psycopg2-binary==2.9.11" \
    "python-dateutil==2.9.0.post0" \
    "lxml==6.0.2" \
    "pytest==8.4.2" \
    "pytest-cov==7.0.0"

ENV PYTHONPATH=/oboa/src:/aboa/src:/usr/local/python-packages
ENV PATH="/oboa/src/oboa/scripts:/usr/local/python-packages/bin:${PATH}"

ENV OBOA_RESOURCES_PATH=/oboa/src/oboa/config
ENV OBOA_LOG_PATH=/log
ENV OBOA_SCHEMAS_PATH=/oboa/src/oboa/schemas
ENV OBOA_POLLING_DIR=/oboa_polling
ENV OBOA_PROCESSING_DIR=/oboa_processing
ENV OBOA_ERROR_DIR=/oboa_error
ENV OBOA_DAEMON_PID_FILE=/tmp/oboa.pid
ENV PYTHONDONTWRITEBYTECODE=1
ENV LC_ALL=en_US.utf-8
ENV LANG=en_US.utf-8

WORKDIR /oboa

USER boa

# Install datamodel
RUN ln -s /oboa/src/oboa/datamodel/oboa_data_model.sql /datamodel

CMD ["/bin/bash", "-c", "/oboa/src/oboa/scripts/start_oboa.sh"]
